### ISSUE TITLE
[Suggestion] Hideable NBT Tooltip?

### ISSUE THREAD

**Issue by CalamitousEnd** [CrimsonFluff/Silky-Touch#2]
Sorry to be a pain, but I just wanted to suggest maybe the "NBT Size X/X" thing could be hidden by default?

**Comment by CrimsonFluff** [comment]
its there to serve as a warning against moving large inventories with large nbt data, as that would cause world corruption

just like Dank Storage does

it needs to be there

I could make it only show on blocks that have been silk-touched, but that requires adding more nbt <- this would be a nicer solution

**Comment by CrimsonFluff** [comment]
TODO:

- [ ] Add spawners support
- [ ] Make nbt size tooltip friendlier

**Comment by CrimsonFluff** [comment]
done
