### ISSUE TITLE
[Bug] Cannot place down "Obtained Spawners"

### ISSUE THREAD

**Issue by CalamitousEnd** [CrimsonFluff/Silky-Touch#3]
So...What I mean by that is, say I craft a Zombie Spawner specifically, I cannot place it down because it just vanishes. Can we get a Fix for this?

It's crucial to packs that have a way to obtain monster spawners with specific mobs in them. IE. Skyblock Packs.

**Comment by CrimsonFluff** [comment]
are you using the silk-spawners mod as well as silk-chests?

**Comment by CalamitousEnd** [comment]
Don't tell me the mod "Packing Tape" would conflict with it, would it?

**Comment by CrimsonFluff** [comment]
never heard of that mod.  my mod does seem in fact to be broken

you would think I never test my mods at all  :-(

**Comment by CalamitousEnd** [comment]
Don't sweat it CrimsonFluff, sometimes something works just fine in a Dev environment and in a real environment...it breaks. Ain't your fault, I am sure you've done extensive testing. :)

**Comment by CrimsonFluff** [comment]
so...  I spawned a spawner, placed it, changed to a sheep spawner using a spawn egg
broke the spawner with silk pickaxe and placed it down

all seems ok

**Comment by CalamitousEnd** [comment]
So...I'm not exactly "crafting them" I obtain them through a Custom Trade I made for a Wandering Trader. Weird thing is this, without Crimson Silky Touch, it let's me plant them down just fine. I've all ready gone through the trouble shooting with the Developer of "Custom Villager Trades". When your mod is installed...Poof. Spawner goes bye bye.

**Comment by CalamitousEnd** [comment]
Hang on, I am gonna test it with 'in world' spawners.

**Comment by CrimsonFluff** [comment]
it seems if you spawn a spawner in using command, then place, it vanishes

**Comment by CalamitousEnd** [comment]
Yep. That does the same for me as well.

**Comment by CrimsonFluff** [comment]
so i just did `locate minecraft:mineshaft` and broke a spider spawner and placed it - all was ok

can you try too, please

**Comment by CalamitousEnd** [comment]
Doing so right now.

**Comment by CalamitousEnd** [comment]
Breaking a Spider Spawner and Replacing it works fine.

**Comment by CalamitousEnd** [comment]
The issue seems to only occur when a Player is given a Spawner with NBT Data through some sort of means.

**Comment by CrimsonFluff** [comment]
Ive just looked at Packing Tape.  It is a far better mod than mine (its also by a Forge top ranking member)

I wouldnt use my mod with Packing Tape as they pretty much do the same thing - Packing Tape *should* also work on Spawners

**Comment by CalamitousEnd** [comment]
See, the point in my case of having a mod like yours or Packing Tape is for when I don't have a Silk Touch Pickaxe. Lol

**Comment by CrimsonFluff** [comment]
I would stick with Packing Tape and maybe make it cheaper for the player if you're putting your own modpack together

**Comment by CalamitousEnd** [comment]
Eh I want to use both though. I got reasons. Haha

**Comment by CalamitousEnd** [comment]
Anyway, my questionable mod combination choices aside...

Hopefully this'll be an easy fix. :)

**Comment by CrimsonFluff** [comment]
Ive fixed it - stoopid mistake

note to self - stop being stoopid

although, when I spawn a spawner in with `/give @s spawner{SpawnData:{id:"minecraft:cow"},Delay:299}`, when placed it always defaults to pig

not sure if thats a fault of my mod?

**Comment by CalamitousEnd** [comment]
That's a Vanilla Fault with Commands. Not your problem.

**Comment by CrimsonFluff** [comment]
ive fixed 1.17.1, i'll do 1.16.5 and upload shortly

**Comment by CalamitousEnd** [comment]
Thank you for being so quick to respond and fix the issue. Is it safe for me to close my issue?

**Comment by CrimsonFluff** [comment]
yeah, go ahead

thanks for testing :-)
